### ISSUE TITLE
Errors in time format parsing

### ISSUE THREAD

**Issue by parasit** [Tomohiro/fluentular#140]
Hey, 
In one of my application i have time in format:
`2018-03-01T13:02:03.443149+00:00`
This format should be recognized by:
`%Y-%m-%dT%H:%M:%S.%6N%z`
But in your application i got error:
`Error: invalid time format: value = 2018-03-01T13:02:03.443149+00:00, error_class = ArgumentError, error = invalid strptime format - '%Y-%m-%dT%H:%M:%S.%6N%z'`

Problem is in `%6N` part, which is not accepted, without this everything else is ok.

BR
Parasit

**Comment by Tomohiro** [comment]
@parasit 
Can not support `%6N`. So this is correct behavior.

I quote the Fluentd document:

> Use %N to parse subsecond, because strptime does not support %3N, %6N, %9N, and %L

References:
* https://docs.fluentd.org/v1.0/articles/parse-section#time-parameters
