### ISSUE TITLE
your site is show Internal Server Error

### ISSUE THREAD

**Issue by feiyu563** [Tomohiro/fluentular#141]
your site is show Internal Server Error
![image](https://user-images.githubusercontent.com/25146052/40407769-152c9f52-5e98-11e8-901a-b9afafa5e33d.png)
![image](https://user-images.githubusercontent.com/25146052/40407780-1faf7242-5e98-11e8-89b6-760c19eea96c.png)

**Comment by Tomohiro** [comment]
I've fixed it in #144
