### ISSUE TITLE
fluentular.herokuapp.com is down :(

### ISSUE THREAD

**Issue by jesper** [Tomohiro/fluentular#75]
http://fluentular.herokuapp.com/

Shows "Application Error"

**Comment by Tomohiro** [comment]
Thanks for your report. http://fluentular.herokuapp.com/ is demo site.

Currently, Fluentular uses [Free Dynos][] on Heroku that awake time is max 18hrs/day. If you saw "Application Error" when dyno is sleeping.

However you can deploy Fluentular on Heroku (this is your app) by using "[Heroku Button][]" if your want to use Fluentular at any time.

Alternatively, if you are using Docker, you can launch a Fluentular container from [Docker Hub][].

[Free Dynos]: https://devcenter.heroku.com/articles/dyno-types#available-dyno-types
[Heroku Button]: https://github.com/Tomohiro/fluentular#heroku-ready
[Docker Hub]: https://hub.docker.com/r/tomohiro/fluentular/

**Comment by jesper** [comment]
Thanks for the tips @Tomohiro!
